services:
  node:
    build: .
    ports:
      - "3000:3000"
    links:
      - pocketbase

  pocketbase:
    build: ./pocketbase
    ports:
      - "8090:8090"
    volumes:
      - /pb/pb_data:/pb/pb_data
