services:
  node:
    build: .
    image: harbor.halfpipe.dev/lth/node:latest
    ports:
      - "3000:3000"
    links:
      - pocketbase
    environment:
      - POCKETBASE_URL=${POCKETBASE_URL}

  pocketbase:
    build: ./pocketbase
    image: harbor.halfpipe.dev/lth/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data

volumes:
  pb_data:
