name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: download changes, build and run containers
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                script: |
                    cd /var/www/lth
                    git pull
                    docker compose down
                    docker compose up -d --build --force-recreate
                    docker image prune -f